In [6]:
import pandas as pd
import numpy as np

In [7]:
data=[60,90,80,85,70]
print (np.mean (data))

77.0

In [9]:
print (np.median(data))

80.0

In [10]:
from scipy import stats

In [11]:
print ("most frequent values will be",stats.mode(data))

most frequent values will be ModeResult(mode=np.int64(60), count=np.int64(1))

In [12]:
print(max(data)-min(data))

30

In [14]:
print("variance",np.var(data))

variance 116.0

In [15]:
print("SD",np.std(data))

SD 10.770329614269007

In [20]:
df=pd.DataFrame(data)
df

    0
0  60
1  90
2  80
3  85
4  70

In [22]:
df.describe()

               0
count   5.000000
mean   77.000000
std    12.041595
min    60.000000
25%    70.000000
50%    80.000000
75%    85.000000
max    90.000000

In [23]:
pop= [45,50,55,60,65,70,75,80,85,90,
        52,58,63,67,72,77,82,88,91,95,
        40,48,53,59,64,69,74,79,84,89,
        46 ,51,57,62,66,71,76,81,86,92,
        44,49,54,61,68,73,78,83,87,93]

In [25]:
print(np.var(pop))

225.7604

In [26]:
import random

In [36]:
samp =random .sample(pop, 15)
print(samp)

[40, 91, 71, 54, 81, 64, 57, 50, 78, 60, 51, 53, 93, 79, 49]

In [39]:
print(np.var(samp))

251.5288888888889

In [43]:
sample = np.var(pop,ddof=1)
print (sample)

230.36775510204083